### PR TITLE
basic registration/login

### PR DESCRIPTION
**Pull request by RachellCalhoun**
https://github.com/dawnwages/wagtail-indymeet/issues/30

### CODE REVIEW

**Comment by RachellCalhoun** [comment]
@dawnwages  this is just a basic registration and login ...not very pretty but I wanted to get it functional first so you can do what you'd like with it.

**Comment by dawnwages** [comment]
I did some of this too! my fault. I'm going to merge your branch into mine and default to your changes.

**Comment by dawnwages** [comment]
Can't merge! I'm sure there's some of the same stuff between the two. I'll stop going rogue now. If you want to check it out and try to resolve the differences, its https://github.com/dawnwages/wagtail-indymeet/pull/32

I'm going to be away from my keyboard all tomorrow so if you want to merge my two commits into a working branch -- we should probably now have a `develop` branch. They're straightforward and complete.

**Comment by RachellCalhoun** [comment]
@dawnwages 
This is great, thanks for all your work on #32! :tada:  I was able to merge it with only a few places that I had to choose one way or the other or make changes: 

- followed documentation example for urls :  https://docs.djangoproject.com/en/4.1/topics/http/urls/#including-other-urlconfs
- I renamed the profile function to lowercase. https://peps.python.org/pep-0008/#function-and-variable-names

I noticed django-bootstrap has been removed, I don't know if this was intentional, but wanted to draw attention. 

I saw you added Black and Flake. YAY! I did not run any formatter on this because it's a bit complicated. Let's set up an automated (?) process and add documentation to for running these. And maybe we do a run on a clean branch.

**Comment by dawnwages** [comment]
yes let's set up github CI/CD? re; I saw you added Black and Flake. YAY! I did not run any formatter on this because it's a bit complicated. Let's set up an automated (?) process and add documentation to for running these. And maybe we do a run on a clean branch.

I've also wanted to use pre-commit on a personal project but haven't gotten around to it. I'd have to fiddle my way through both so I'm happy to go through the least complicated path :) If you have a preference, I'm not particular.

**Comment by dawnwages** [comment]
ahh dope! Reviewed :) 

LGTM!

**Review by dawnwages — APPROVED** [review]

**Pull request merged**
